# Generated by Django 4.1.4 on 2022-12-27 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('to_remove', models.DateTimeField(default=False, verbose_name='Помечен на удаление')),
                ('document_type', models.CharField(choices=[('income', 'Приход'), ('expense', 'Расход')], max_length=10, verbose_name='Тип документа')),
                ('apply_flag', models.BooleanField(default=False, verbose_name='Документ проведен')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('to_remove', models.DateTimeField(default=False, verbose_name='Помечен на удаление')),
                ('drink_name', models.CharField(max_length=100, verbose_name='Название напитка')),
            ],
            options={
                'verbose_name': 'Напиток',
                'verbose_name_plural': 'Напитки',
                'ordering': ['drink_name'],
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('to_remove', models.DateTimeField(default=False, verbose_name='Помечен на удаление')),
                ('title', models.CharField(max_length=250, verbose_name='Наименование')),
                ('unit', models.CharField(max_length=20, verbose_name='Единица измерения')),
                ('category', models.CharField(choices=[('product', 'Продукт'), ('tare', 'Тара'), ('snack', 'Штучный товар')], max_length=20, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True, verbose_name='Пользователь')),
                ('operation', models.TextField(verbose_name='Операция')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время операции')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='StorageItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('to_remove', models.DateTimeField(default=False, verbose_name='Помечен на удаление')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cafecrm.goods', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Остаток',
                'verbose_name_plural': 'Остатки',
            },
        ),
        migrations.CreateModel(
            name='DrinkRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('drink_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafecrm.drinks', verbose_name='Напиток')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cafecrm.goods', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='DocumentItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafecrm.documents', verbose_name='Документ')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cafecrm.goods', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в документе',
                'verbose_name_plural': 'Товары в документе',
            },
        ),
    ]
