# Generated by Django 4.1.4 on 2022-12-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafecrm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drinkrecipes',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
