# Generated by Django 4.1.4 on 2022-12-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafecrm', '0002_alter_drinkrecipes_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='unit',
            field=models.CharField(choices=[('pc', 'шт.'), ('ml', 'мл'), ('gr', 'гр')], max_length=20, verbose_name='Единица измерения'),
        ),
    ]
