# Generated by Django 4.1.4 on 2022-12-27 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cafecrm', '0003_alter_goods_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='storageitems',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='storageitems',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения'),
        ),
    ]
