# Generated by Django 4.1.4 on 2022-12-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafecrm', '0004_alter_documents_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='to_remove',
            field=models.BooleanField(default=False, verbose_name='Помечен на удаление'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='to_remove',
            field=models.BooleanField(default=False, verbose_name='Помечен на удаление'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='to_remove',
            field=models.BooleanField(default=False, verbose_name='Помечен на удаление'),
        ),
        migrations.AlterField(
            model_name='storageitems',
            name='to_remove',
            field=models.BooleanField(default=False, verbose_name='Помечен на удаление'),
        ),
    ]
