# Generated by Django 4.1.4 on 2022-12-28 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafecrm', '0007_documentitems_documents_operations_storageitems_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentitems',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documentitems',
            name='good',
        ),
        migrations.DeleteModel(
            name='Operations',
        ),
        migrations.RemoveField(
            model_name='storageitems',
            name='item',
        ),
        migrations.DeleteModel(
            name='DocumentItems',
        ),
        migrations.DeleteModel(
            name='Documents',
        ),
        migrations.DeleteModel(
            name='StorageItems',
        ),
    ]
