# Generated by Django 4.1.4 on 2022-12-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafecrm', '0008_remove_documentitems_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkrecipes',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
