# Generated by Django 4.1.4 on 2022-12-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafecrm', '0009_alter_drinkrecipes_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DrinkRecipes',
            new_name='DrinkItems',
        ),
    ]
