# Generated by Django 4.1.4 on 2022-12-29 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafecrm', '0010_rename_drinkrecipes_drinkitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinks',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='drinks',
            name='to_remove',
        ),
        migrations.RemoveField(
            model_name='drinks',
            name='update_date',
        ),
    ]
