# Generated by Django 4.1.4 on 2022-12-30 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafecrm', '0011_remove_drinks_create_date_remove_drinks_to_remove_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('unit', models.CharField(choices=[('pc', 'pc'), ('ml', 'ml'), ('gr', 'gr')], max_length=20, verbose_name='Единица измерения')),
                ('product_type', models.CharField(choices=[('product', 'product'), ('snack', 'snack'), ('tare', 'tare')], max_length=20, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['product_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='drinkitems',
            options={'verbose_name': 'Ингридиент', 'verbose_name_plural': 'Ингридиенты'},
        ),
        migrations.AlterField(
            model_name='drinkitems',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cafecrm.products', verbose_name='Продукт'),
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
    ]
