# Generated by Django 4.1.4 on 2023-01-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafecrm', '0012_products_alter_drinkitems_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='drinkitems',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_type',
            field=models.CharField(choices=[('product', 'продукт'), ('snack', 'штучный товар'), ('tare', 'тара')], max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='products',
            name='unit',
            field=models.CharField(choices=[('шт.', 'шт.'), ('мл', 'мл'), ('гр', 'гр')], max_length=20, verbose_name='Единица измерения'),
        ),
    ]
