# Generated by Django 4.1.4 on 2023-01-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafecrm', '0013_products_price_products_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
