# Generated by Django 4.1.4 on 2023-01-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafecrm', '0018_alter_drinkitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinks',
            name='slug',
            field=models.SlugField(default='-', max_length=200, unique='drink_name'),
        ),
    ]
