# Generated by Django 4.1.4 on 2023-01-06 12:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cafecrm', '0022_alter_products_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, max_length=200, unique='drink_name'),
        ),
    ]
