# Generated by Django 4.1.4 on 2023-01-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafecrm', '0023_alter_drinks_slug'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='products',
            index_together={('id', 'slug')},
        ),
        migrations.DeleteModel(
            name='DrinkItems',
        ),
        migrations.DeleteModel(
            name='Drinks',
        ),
    ]
