# Generated by Django 4.1.4 on 2023-01-07 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafecrm', '0024_alter_products_index_together_delete_drinkitems_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Drink',
                'verbose_name_plural': 'Drinks',
                'ordering': ('drink_name',),
            },
        ),
        migrations.CreateModel(
            name='DrinkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='cafecrm.drink')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drink_items', to='cafecrm.products')),
            ],
        ),
    ]
