# Generated by Django 4.1.4 on 2023-01-09 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafecrm', '0025_drink_drinkitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='slug',
            field=models.SlugField(blank=True, unique='drink_name'),
        ),
        migrations.AlterField(
            model_name='drinkitem',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cafecrm.drink'),
        ),
    ]
