# Generated by Django 4.1.4 on 2023-01-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafecrm', '0026_drink_slug_alter_drinkitem_drink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(max_length=200, unique='product_name'),
        ),
    ]
