# Generated by Django 4.1.4 on 2023-01-10 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafecrm', '0027_alter_products_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Receipt', 'Receipt'), ('Consumption', 'Consumption')], max_length=20, verbose_name='document type')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cafecrm.document')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_items', to='cafecrm.products')),
            ],
        ),
    ]
