# Generated by Django 4.1.4 on 2023-01-10 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafecrm', '0033_selling_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selling',
            old_name='description',
            new_name='comments',
        ),
    ]
