# Generated by Django 4.1.4 on 2023-01-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafecrm', '0034_rename_description_selling_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='min_stock',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
