# Generated by Django 4.1.4 on 2023-01-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafecrm', '0035_products_min_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='selling',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Пользователь'),
        ),
    ]
