# Generated by Django 4.1.4 on 2023-01-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafecrm', '0036_selling_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellingitem',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Пользователь'),
        ),
    ]
