# Generated by Django 4.1.4 on 2023-01-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafecrm', '0039_remove_selling_author_document_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selling',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
    ]
