# Generated by Django 4.1.4 on 2023-01-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafecrm', '0040_alter_selling_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='menu_type',
            field=models.SmallIntegerField(default=1),
        ),
    ]
