# Generated by Django 4.1.4 on 2023-01-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafecrm', '0041_drink_menu_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='menu_type',
            field=models.CharField(choices=[('drink', 'напиток'), ('snack', 'штучный товар')], max_length=20, verbose_name='Категория'),
        ),
    ]
