# Generated by Django 4.1.4 on 2023-01-31 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafecrm', '0042_alter_drink_menu_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('Приход', 'Приход'), ('Расход', 'Расход')], max_length=20, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cafecrm.document', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='drink_name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='drinkitem',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cafecrm.drink', verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='sellingitem',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafecrm.drink', verbose_name='Товар'),
        ),
    ]
