# Generated by Django 4.1.4 on 2023-02-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafecrm', '0043_alter_document_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='min_stock',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Минимальный остаток'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Остаток'),
        ),
    ]
