# Generated by Django 4.1.4 on 2023-02-03 15:39

from django.db import migrations
from django.db import models

class Migration(migrations.Migration):

    dependencies = [
        ('cafecrm', '0044_alter_products_min_stock_alter_products_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='price',
            field=models.DecimalField(max_digits=10, decimal_places=2, default=0.00, verbose_name='Цена', blank=True, null=True),
        ),
    ]
