# Generated by Django 4.1.4 on 2023-02-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafecrm', '0045_auto_20230203_1639'),
    ]

    operations = [
    ]
